stages:
  - build
  - test
  - staging
  - production

build:
  image: node:latest
  stage: build
  artifacts:
    untracked: true
  before_script:
    - cd ./client && npm ci
    - cd ../server && npm ci
  script:
    - cd ../client && npm run build

test:
  image: node:latest
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: testing
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test_pass
  dependencies:
    - build
  script:
    - psql -h "localhost" -U "test" -d "testing" -c "SELECT 'OK' AS status;"
    - cd ./client && npm test
    - cd ../server && npm test

staging:
  image: docker:latest
  stage: staging
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASS
  script:
    - docker build -t $CI_DOCKER_USERNAME/oddity:staging .
    - docker push $CI_DOCKER_USERNAME/oddity:staging

production:
  image: docker:latest
  stage: production
  services:
    - docker:dind
  when: manual
  before_script:
    - docker info
    - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASS
  script:
    - docker build -t $CI_DOCKER_USERNAME/oddity:production .
    - docker push $CI_DOCKER_USERNAME/oddity:production
