stages:
  - build
  - test
  - deploy

build:
  image: node:latest
  stage: build
  artifacts:
    untracked: true
  before_script:
    - cd ./client && npm ci
    - cd ../server && npm ci
  script:
    - cd ../client && npm run build

test:
  image: node:latest
  stage: test
  dependencies:
    - build
  script:
    - cd ./client && npm test
    - cd ../server && npm test

deploy:
  stage: deploy
  before_script:
    - apt update && apt install curl
    - curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
  script:
    - docker-compose up
