stages:
  # - build
  # - test
  - staging
  - production

# build:
#   image: node:latest
#   stage: build
#   artifacts:
#     untracked: true
#   before_script:
#     - cd ./client && npm ci
#     - cd ../server && npm ci
#   script:
#     - cd ../client && npm run build

# test:
#   image: node:latest
#   stage: test
#   dependencies:
#     - build
#   script:
#     - cd ./client && npm test
#     - cd ../server && npm test

staging:
  image: docker:latest
  stage: staging
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASS
  # before_script:
  # - apk --no-cache add curl
  # - curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
  # - chmod +x docker-compose
  script:
    - docker build -t oddityservers/oddity:staging .
    - docker push oddityservers/oddity:staging

production:
  image: docker:latest
  stage: production
  services:
    - docker:dind
  when: manual
  before_script:
    - docker info
    - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASS
  script:
    - docker build -t oddityservers/oddity:production .
    - docker push oddityservers/oddity:production
