image: docker:latest

before_script:
  - pwd
  - docker info

stages:
  - deploy_staging
  - deploy_production

staging:
  stage: deploy_staging
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASS
  script:
    - docker build -t $CI_DOCKER_USERNAME/oddity .
    - docker push $CI_DOCKER_USERNAME/oddity:staging
    - mkdir image && cd image
    - docker export $CI_DOCKER_USERNAME/oddity > oddity.tar
  artifacts:
    path: ~/image/

production:
  stage: deploy_production
  services:
    - docker:dind
  when: manual
  before_script:
    - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASS
  script:
    - docker load --input image/oddity.tar
    - docker build -t $CI_DOCKER_USERNAME/oddity:production .
    - docker push $CI_DOCKER_USERNAME/oddity:production
