image: docker:latest

services:
  - docker:dind

build:
  script:
    - docker build -t $CI_DOCKER_USERNAME/oddity:latest .

test:
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: testing
    POSTGRES_USER: test
    PGPASSWORD: test_pass
  dependencies:
    - build
  script:
    - cd ./client && npm test
    - cd ../server && DB_HOST=postgres npm test

deploy:
  before_script:
    - docker info
    - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASS
  script:
    - docker build -t $CI_DOCKER_USERNAME/oddity:staging .
    - docker push $CI_DOCKER_USERNAME/oddity:staging

production:
  when: manual
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASS
  script:
    - docker build -t $CI_DOCKER_USERNAME/oddity:production .
    - docker push $CI_DOCKER_USERNAME/oddity:production
