#
# Development Build: client + server
#


FROM node:latest

# App Directory
WORKDIR /usr/src/app

# Moves files to App Directory
COPY . /usr/src/app

# Build Server
WORKDIR /usr/src/app/server
RUN npm ci

# Create module_loader_imports file
RUN node module_loader

# Link node_modules for modules
WORKDIR /usr/src/app
RUN ln -fs "$(pwd)/server/node_modules" "$(pwd)/modules/" 

# Build Client
WORKDIR /usr/src/app/client
RUN npm ci

# Start App
WORKDIR /usr/src/app/server

CMD cd ../client && npm start & npm start
EXPOSE 5000
