#
# Production ready docker compose
#

version: "2"
services:
  oddity:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: oddity
      DB_USERNAME: oddity
      DB_PASSWORD: oddity_pass
      SESSION_SECRET: string_longer_than_32_characters
      CAPTCHA_CLIENT: client_captcha
      CAPTCHA_SERVER: server_captcha
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: oddity
      POSTGRES_DB: oddity
      POSTGRES_PASSWORD: oddity_pass
